// let hello = "hello";
// let owu ="owu";
// let com="com";
// let ua="ua";
// let one=1;
// let ten=10;
// let nine=-999;
// let oneTwo=123;
// let three=3.14;
// let two=2.7;
// let sixteen=16;
// let t=true; 
// let f=false;
// console.log(hello);
// alert(hello);
// document.write(hello);
// console.log(owu);
// alert(owu);
// document.write(owu);
// console.log(com);
// alert(com);
// document.write(com);
// console.log(ua);
// alert(ua);
// document.write(owu);
// console.log(one);
// alert(one);
// document.write(one);
// console.log(ten);
// alert(ten);
// document.write(ten);
// console.log(nine);
// alert(nine);
// document.write(nine);
// console.log(oneTwo);
// alert(oneTwo);
// document.write(oneTwo);
// console.log(three);
// alert(three);
// document.write(three);
// console.log(two);
// alert(two);
// document.write(two);
// console.log(sixteen);
// alert(sixteen);
// document.write(sixteen);
// console.log(t);
// alert(t);
// document.write(t);
// console.log(f);
// alert(f);
// document.write(f);

//  hello = "bye";
//  owu ="uwo";
//  com="moc";
//  ua="rus";
//  one=-1;
//  ten=-10;
//  nine=999;
//  oneTwo=-123;
//  three=14.3;
//  two=7.2;
//  sixteen=61;
//  t=false; 
// f=true;
// console.log(hello,owu,com,ua,one,ten,nine,oneTwo,three,two,sixteen,t,f);
// alert(hello,owu,com,ua,one,ten,nine,oneTwo,three,two,sixteen,t,f);
// document.write(hello,owu,com,ua,one,ten,nine,oneTwo,three,two,sixteen,t,f);

// const a=3;
// const b=5;
// const c=6;
// const q="Hello";
// const w="Привет";
// const e="Привіт";
// console.log(a,b,c,q,w,e);
// alert(a,b,c,q,w,e);
// document.write(a,b,c,q,w,e);

// let name=prompt("name");
// let surname=prompt(" surname");
// let patronymic=prompt("patronymic");
//  console.log(name,surname,patronymic);
//  alert(name,surname,patronymic);
//  document.write(name,surname,patronymic);
// let person={name,surname,patronymic};
// console.log(person);

//  let a = +prompt("a");
//  let b =+prompt("b");
//  let c= +prompt("c");
//  console.log(a,b,c);

// let a=parseInt(prompt("a"));
// let b=parseInt(prompt("b"));
// let c=parseInt(prompt("c"));
// let d=parseInt(prompt("d"));
// let result={a,b,c,d};
// console.log(a,b,c,d);

// let a=parseFloat(prompt("a"));
// let b=parseFloat(prompt("b"));
// let c=parseFloat(prompt("c"));
// let result={a,b,c};
// console.log(result);



